### ISSUE TITLE
There are database errors after start program

### ISSUE THREAD

**Issue by javadev** [konachan700/JNekoImageDB#7]
☆ 1455785036169 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: albums
☆ 1455785036171 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: images
☆ 1455785036173 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: img_alb
☆ 1455785036174 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: img_tag
☆ 1455785036175 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: longpairs
☆ 1455785036177 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: prevsz
☆ 1455785036179 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: stringpairs
☆ 1455785036180 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: tags
☆ 1455785036181 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: albums
☆ 1455785036182 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: images
☆ 1455785036183 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: img_alb
☆ 1455785036184 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: img_tag
☆ 1455785036185 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: longpairs
☆ 1455785036186 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: prevsz
☆ 1455785036187 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: stringpairs
☆ 1455785036188 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: tags
☆ 1455785036189 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: albums
☆ 1455785036190 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: images
☆ 1455785036191 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: img_alb
☆ 1455785036192 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: img_tag
☆ 1455785036192 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: longpairs
☆ 1455785036193 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: prevsz
☆ 1455785036194 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: stringpairs
☆ 1455785036195 INFO [java.sql.DatabaseMetaData]
        HHH000262: Table not found: tags

**Comment by georgy7** [comment]
@konachan700 If you used Spring IoC, you could use Liquibase (Spring bean) for DB initialization.
http://www.liquibase.org/documentation/spring.html

**Comment by konachan700** [comment]
Это инфо от хибернейта, я БД напрямую не дергаю. Насколько я понимаю, при первом запуске так быть и должно, поскольку БД создается новая. Это не ошибка, это просто инфо о том, что хибернейт не нашел таблицу и создал новую.
Сразу после старта надо создать типы превью, выбрать дефолтный и перезапустить программу - пока нет меню инициализации базы при старте. Иначе работать не будет.

**Comment by javadev** [comment]
Ага, тогда можно закрывать.
