### ISSUE TITLE
Сломан GUI

### ISSUE THREAD

**Issue by sirikid** [konachan700/JNekoImageDB#8]
Ванильная Windows 10, транк, программа выглядит так
![jnidb0](https://cloud.githubusercontent.com/assets/4840430/13938894/ef78fa76-efe0-11e5-9885-de1f26610639.PNG)
**PS** Кроме того ещё и куча ворнингов от IDEA аля final на static методах.

**Comment by konachan700** [comment]
Это однозначно в папке с программой нет папки ./style/*

> PS Кроме того ещё и куча ворнингов от IDEA аля final на static методах.

А где именно, можно список? Вроде бы не должно быть такого, я редко делаю методы финальными вообще.

**Comment by sirikid** [comment]
Эх, а я подумал что Maven standalone jar соберет. Методы в GUITools. IDEA выдает 1k предупреждений, 400 на орфографию, остальное тоже в основном мусор.

**Comment by konachan700** [comment]
>  Методы в GUITools.

Спасибо, убрал.

А файл стилей и иконки специально вынес в отдельную папку, чтобы любой мог его поправить по своему вкусу.

**Comment by sirikid** [comment]
Предусмотрительно
