### ISSUE TITLE
Объясни пожалуйста

### ISSUE THREAD

**Issue by georgy7** [konachan700/JNekoImageDB#9]
Программа как-то перемещает фотографии на диске? Или ты просто задаёшь ей директорию, файлы где лежали, там и лежат, но просто добавляется индекс с тегами?
Если она как-то сама организует фотографии на диске, то как именно она это делает?

**Comment by konachan700** [comment]
да, у нее своя БД. В текущей версии загрузка картинок (само окошко) выпилена в связи с очередным рефакторингом, но закончить нет времени из-за других рабочих проектов.
Организация в текущей версии такая. Картинки лежат в виде зашифрованных файлов с именем ./dbFolderName/md5()[0]/md5()[1]/tail(14, md5(fileName)) - нужно, чтобы в одной директории не скапливалось большое количество файлов. 
После рефакторинга все файлы будут лежать в kv-базе данных, поскольку хранение в виде отдельных файлов сильно осложняет бекап: стогигабайтный файл NoSQL копируется со скоростью 100-120мб\с на хорошем харде, а тысячи мелких файлов на эти же сто гигов даже в многопоточном режиме копирования хорошо если 30-40мб\с выдают, обычно сильно меньше. Да, в NoSQL файлы хранить не рекомендуется, но это справедливо для серверного применения, для десктопного все наоборот, важно именно удобство использования. Все файлы внутри базы будут кодироваться ХОR-ом для того, чтобы апвтоматические распознователи контента, например, как у гугл диска, не могли понять, что внутри файла. Настоящее шифрование (RSA/AES256) будет включаться самим пользователем, если оно нужно.

**Comment by georgy7** [comment]
Спасибо за разъяснение 😄
Мне самому шифрование то и не нужно, но нужен удобный инструмент, чтобы хранить личные фото. Их слишком много. И их сейчас никак нельзя разложить в виде древовидной структуры каталогов.

**Comment by georgy7** [comment]
Для меня большущую важность имеет потенциальная возможность восстановить поврежденную базу и даже восстановить поврежденные фотографии из него (отличается несколько байт, например). Мне совсем не хочется терять все свои фотографии в случае какого-то сбоя HDD/SSD. Т.е. даже если это NoSQL, хорошо бы, чтобы это был простой формат, в котором можно разобраться. Или возможно, чтобы в ПО была возможность перестроить индекс картинок, если индекс был поврежден, а не сами картинки.

**Comment by developerdevpav** [comment]
Привет, очень рад, ребята, что вы закрыли таск.   On Wednesday, June 20, 2018, 7:44:37 PM GMT+3, Георгий У. <notifications@github.com> wrote:  
 
 
Closed #9.
